### PR TITLE
Propose default stun option on failed to connect call

### LINKED ISSUE #3251: VoIP: Fallback to matrix.org STUN server with a confirmation dialog
We do not fallback anymore to the Google STUN server but users cannot make call anymore if their HS admin has not set up a STUN server.

We should fallback them to the STUN server available on matrix.org but with their permission.
We should do it when accepting or creating a call. If not possible, that will be another popup at app startup :/

The copy for the permission will come from riot-web: https://github.com/vector-im/riot-web/issues/10173#issuecomment-519874468 and next.

### PR DESCRIPTION
**Pull request by BillCarsonFr**
Fixes #3251

image

image

### Pull Request Checklist

* [ ] Changes has been tested on an Android device or Android emulator with API 16
* [x] UI change has been tested on both light and dark themes
* [x] Pull request is based on the develop branch
* [x] Pull request updates [CHANGES.rst](https://github.com/vector-im/riot-android/blob/develop/CHANGES.rst)
* [x] Pull request includes screenshots or videos if containing UI changes
* [x] Pull request includes a [sign off](https://github.com/matrix-org/synapse/blob/master/CONTRIBUTING.rst#sign-off)

### CODE REVIEW

File: vector/src/main/java/im/vector/fragments/VectorSettingsPreferencesFragment.kt [hunk 1]
```diff
@@ -801,6 +805,23 @@ class VectorSettingsPreferencesFragment : PreferenceFragmentCompat(), SharedPref
             false
         }
 
+        mUseDefaultStunPreference.let {
+            activity?.let { activity ->
+                it.isChecked = PreferencesManager.useDefaultTurnServer(activity)
+                val stun = activity.getString(R.string.default_stun_server)
+                it.summary = activity.getString(R.string.settings_call_ringtone_use_default_stun_sum, stun)
```
Comment (bmarty) [inline vector/src/main/java/im/vector/fragments/VectorSettingsPreferencesFragment.kt]: no need to use `activity` to call `getString()`

File: vector/src/main/java/im/vector/fragments/VectorSettingsPreferencesFragment.kt [hunk 2]
```diff
@@ -801,6 +805,23 @@ class VectorSettingsPreferencesFragment : PreferenceFragmentCompat(), SharedPref
             false
         }
 
+        mUseDefaultStunPreference.let {
+            activity?.let { activity ->
+                it.isChecked = PreferencesManager.useDefaultTurnServer(activity)
```
Comment (bmarty) [inline vector/src/main/java/im/vector/fragments/VectorSettingsPreferencesFragment.kt]: This line is not necessary

File: vector/src/main/java/im/vector/util/PreferencesManager.java [hunk 3]
```diff
@@ -580,6 +582,34 @@ public static boolean useJitsiConfCall(Context context) {
         return PreferenceManager.getDefaultSharedPreferences(context).getBoolean(SETTINGS_USE_JITSI_CONF_PREFERENCE_KEY, true);
     }
 
+    /**
+     * Tells if the default turn server must be used when none is provided by the server
+     *
+     * @param context the context
+     * @return true if the conference call must be done with jitsi.
```
Comment (bmarty) [inline vector/src/main/java/im/vector/util/PreferencesManager.java]: Bad copy paste :)

File: vector/src/main/java/im/vector/activity/VectorCallViewActivity.java [hunk 4]
```diff
@@ -1279,4 +1289,43 @@ public void onSensorChanged(SensorEvent event) {
...
+                    .setPositiveButton(getString(R.string.call_failed_no_ice_use_alt, defaultStun), (dialog, which) -> {
+                        PreferencesManager.setUseDefaultTurnServer(this, true);
+                        MXCallsManager.defaultStunServerUri = defaultStun;
+                        finish();
+                    })
+                    .setNeutralButton(R.string.call_failed_dont_ask_again, (dialog, which) -> {
+                        PreferencesManager.setShouldAskForDefaultTurn(this, false);
+                        finish();
+                    })
+                    .setNegativeButton(R.string.ok, (dialog, which) -> {
```
Comment (bmarty) [inline vector/src/main/java/im/vector/activity/VectorCallViewActivity.java]: Wording: "OK" may be a bit ambiguous (looking at the screenshot). I think "Cancel" will be better

File: vector/src/main/java/im/vector/fragments/VectorSettingsPreferencesFragment.kt (hunk 1 above)
Comment (BillCarsonFr) [reply vector/src/main/java/im/vector/fragments/VectorSettingsPreferencesFragment.kt]: done

File: vector/src/main/java/im/vector/fragments/VectorSettingsPreferencesFragment.kt (hunk 2 above)
Comment (BillCarsonFr) [reply vector/src/main/java/im/vector/fragments/VectorSettingsPreferencesFragment.kt]: It's to be sure to take the correct default value (otherwise it's declared in the pref.xml and in the PrefManager)

File: vector/src/main/java/im/vector/util/PreferencesManager.java (hunk 3 above)
Comment (BillCarsonFr) [reply vector/src/main/java/im/vector/util/PreferencesManager.java]: thx, done

File: vector/src/main/java/im/vector/activity/VectorCallViewActivity.java (hunk 4 above)
Comment (BillCarsonFr) [reply vector/src/main/java/im/vector/activity/VectorCallViewActivity.java]: done
