### PR TITLE
Fix regression on nickname completion

### LINKED ISSUE #2613: Nickname completion of displaynames is broken
Action:
* Type first three letters of someone's displayname

Expected result:
* After a few seconds, see a popup with possible completions

Actual result:
* Nothing happens

Affected versions:
* Latest lazyloading build
  * With lazyloading enabled
  * With lazyloading disabled
* Apparently the latest version released to F-Droid/Google is also affected

---

Completion of matrix IDs works as expected. (`@bla...`)

### PR DESCRIPTION
**Pull request by bmarty**
- Improve string format
- Fix #2613 
- Travis run unit tests

### CODE REVIEW

File: vector/src/test/java/im/vector/util/AutoCompletionModeTest.kt [hunk 1]
```diff
@@ -0,0 +1,72 @@
...
+ */
+
+package im.vector.util
+
+import org.junit.Assert.assertEquals
+import org.junit.Test
+
+class AutoCompletionModeTest {
+    @Test
+    fun userMode_empty() {
```
Comment (ganfra) [inline vector/src/test/java/im/vector/util/AutoCompletionModeTest.kt]: I like to have unit tests name like that : 
methodName_ParamIn_ExceptedResult

getWithText_ClassicText_ShouldReturnUserMode
