### PR TITLE
Bug Fix: E2E: App keeps displaying ignored keyshare requests

### LINKED ISSUE #2191: E2E: App keeps displaying ignored keyshare requests
If the user taps on the "Ignore request" button of the keyshare request dialog, the app will show again the same dialog for the same request at the next startup.

### PR DESCRIPTION
**Pull request by manuroe**
Closes #2191.
Needs https://github.com/matrix-org/matrix-android-sdk/pull/258.

### CODE REVIEW

File: vector/src/main/java/im/vector/KeyRequestHandler.java [hunk 1]
```diff
@@ -358,7 +373,7 @@ public void onSuccess(Void info) {
         mAlertDialog.setOnCancelListener(new DialogInterface.OnCancelListener() {
             @Override
             public void onCancel(DialogInterface dialogInterface) {
-                onDisplayKeyShareDialogClose(false);
+                onDisplayKeyShareDialogClose(false, true);
```
Comment (bmarty) [inline vector/src/main/java/im/vector/KeyRequestHandler.java]: 2nd param should be false in this case, no? User does not want explicitly ignore the request.
Nevermind I think this code is useless cause the dialog is not cancellable

Comment (manuroe) [reply vector/src/main/java/im/vector/KeyRequestHandler.java]: Well, I did not know what setOnCancelListener does. Sorry :|
I let you update it if needed.
