### PR TITLE
Bug Fix  #2941

### LINKED ISSUE #2941: Error message for bad passphrase includes the not-user-friendly string (BAD_MESSAGE_MAC) on the end

### PR DESCRIPTION
**Pull request by BillCarsonFr**
Removed the technical error description from the error 
Fixes #2941

### CODE REVIEW

File: vector/src/main/java/im/vector/fragments/keysbackup/restore/KeysBackupRestoreFromKeyViewModel.kt [hunk 1]
```diff
@@ -66,23 +66,28 @@ class KeysBackupRestoreFromKeyViewModel : ViewModel() {
 
                         override fun onUnexpectedError(e: Exception) {
                             sharedViewModel.loadingEvent.value = null
-                            recoveryCodeErrorText.value = context.getString(R.string.keys_backup_recovery_code_error_decrypt, e.localizedMessage)
+                            recoveryCodeErrorText.value = context.getString(R.string.keys_backup_recovery_code_error_decrypt)
+                            Log.e(LOG_TAG, "## onUnexpectedError ${e.localizedMessage}")
```
Comment (bmarty) [inline vector/src/main/java/im/vector/fragments/keysbackup/restore/KeysBackupRestoreFromKeyViewModel.kt]: Add `e` as a last param to log also the stack trace

File: vector/src/main/java/im/vector/fragments/keysbackup/restore/KeysBackupRestoreFromPassphraseViewModel.kt [hunk 2]
```diff
@@ -68,22 +68,28 @@ class KeysBackupRestoreFromPassphraseViewModel : ViewModel() {
 
                         override fun onUnexpectedError(e: Exception) {
                             sharedViewModel.loadingEvent.value = null
-                            passphraseErrorText.value = context.getString(R.string.keys_backup_passphrase_error_decrypt, e.localizedMessage)
+                            passphraseErrorText.value = context.getString(R.string.keys_backup_passphrase_error_decrypt)
+                            Log.e(LOG_TAG, "## onUnexpectedError ${e.localizedMessage}")
```
Comment (bmarty) [inline vector/src/main/java/im/vector/fragments/keysbackup/restore/KeysBackupRestoreFromPassphraseViewModel.kt]: same remark
