### PR TITLE
wellknown in login + rework of fallback Activity

### LINKED ISSUE #3002: Handle well-known data in the login response
@manuroe commented on [Tue Feb 26 2019](https://github.com/vector-im/riot-meta/issues/271)

As described in [MSC1730: Mechanism for redirecting to an alternative server during login](https://github.com/matrix-org/matrix-doc/pull/1730).

JS PR: https://github.com/matrix-org/matrix-react-sdk/pull/2384.

### LINKED ISSUE #3006: Handle device_id returned from the fallback login page
@manuroe commented on [Wed Feb 27 2019](https://github.com/vector-im/riot-ios/issues/2301)

Else crypto will barely work

### LINKED ISSUE #3018: Cryptography is disabled when logging in
I have a homeserver which supports both SSO and password authentication. When logging in via either of the two methods I get a prompt reading "Riot now supports end-to-end encryption but you need to log in again to enable it", if I click "OK" I'm prompted to log in again, and after doing so I get the same message telling me to log in again...

If I tap on "Later" and go to settings to enable encryption the app crashes (the crash log is similar to the one being addressed by #3012)

### LINKED ISSUE #3025: Support SSO in mobile apps
@manuroe commented on [Mon Mar 04 2019](https://github.com/vector-im/riot-meta/issues/276)

If an homeserver requires SSO, mobile apps should allow it nicely like web.

Current display on Riot-iOS:
simulator screen shot - iphone 6s plus - 2019-03-01 at 08 51 29

Riot-Web:
screenshot 2019-03-01 at 07 40 32

### PR DESCRIPTION
**Pull request by bmarty**
Require https://github.com/matrix-org/matrix-android-sdk/pull/440

This PR contains several things regarding login:
- Rework of fallback by merging duplicated code
- Fixes #3018 
- Fixes #3002 
- Fixes #3006 
- Fixes #3025 
- Fixes issue in setting. Separator is always behind its corresponding section.

### CODE REVIEW

File: vector/src/main/java/im/vector/activity/FallbackAuthenticationActivity.kt [hunk 1]
```diff
@@ -0,0 +1,331 @@
...
+
+    // home server url
+    private var mHomeServerUrl: String? = null
+
+    // Mode (MODE_LOGIN or MODE_REGISTER)
+    private var mMode = MODE_LOGIN
+
+    override fun getLayoutRes() = R.layout.activity_authentication_fallback
+
+    override fun getTitleRes(): Int {
```
Comment (BillCarsonFr) [inline vector/src/main/java/im/vector/activity/FallbackAuthenticationActivity.kt]: ternary? = if (mMode == MODE_LOGIN) R.string.login else R.string.create_account

Comment (bmarty) [reply vector/src/main/java/im/vector/activity/FallbackAuthenticationActivity.kt]: Done
