### PR TITLE
Feature/fix infinite restart expired cred

### LINKED ISSUE #3249: Application crashes with infinite loop after 24 hours
gif_temp

(It's not demonstrated in the GIF, but Riot will keep opening and closing unless I quickly open another app.)

Since this is occuring after about 24 hours, I'm assuming this has something to do with token renewal. I pulled the logs, and those seem to confirm that suspicion. A similar issue also occurs on RiotX, but instead of infinitely looping it just logs me out after 24 hours.

```
08-13 20:09:12.108 26454 26454 D ViewRootImpl@a1aaf9c[VectorHomeActivity]: setView = DecorView@d677cea[VectorHomeActivity] TM=true MM=false
08-13 20:09:12.109 26454 26454 E PushManager: registerToThirdPartyServer onMatrixError M_UNKNOWN_TOKEN
08-13 20:09:12.111 26454 26454 E Matrix  : ## createSession() : onConfigurationError M_UNKNOWN_TOKEN
08-13 20:09:12.111 26454 26454 E Matrix  : ## createSession() : onTokenCorrupted
08-13 20:09:12.112  1337  2046 D WifiPermissionsUtil: canAccessScanResults: pkgName = com.sec.android.sdhms, uid = 1000
08-13 20:09:12.115 26454 26594 I System.out: (HTTPLog)-Static: isSBSettingEnabled false
08-13 20:09:12.115 26454 26454 I EventStreamServiceX: sendAction im.vector.services.EventStreamServiceX.LOGOUT
08-13 20:09:12.115 26454 26594 I System.out: (HTTPLog)-Static: isSBSettingEnabled false
08-13 20:09:12.118 26454 26454 E MXSession: Use of a released session
08-13 20:09:12.118 26454 26454 E MXSession: java.lang.Exception: Use of a released session
08-13 20:09:12.118 26454 26454 E MXSession: 	at org.matrix.androidsdk.MXSession.checkIfAlive(MXSession.java:372)
08-13 20:09:12.118 26454 26454 E MXSession: 	at org.matrix.androidsdk.MXSession.getDataHandler(MXSession.java:438)
08-13 20:09:12.118 26454 26454 E MXSession: 	at org.matrix.androidsdk.MXSession.getDataHandler(MXSession.java:128)
08-13 20:09:12.118 26454 26454 E MXSession: 	at org.matrix.androidsdk.crypto.internal.MXCryptoImpl.close(MXCryptoImpl.java:615)
08-13 20:09:12.118 26454 26454 E MXSession: 	at org.matrix.androidsdk.MXSession.enableCrypto(MXSession.java:2465)
08-13 20:09:12.118 26454 26454 E MXSession: 	at org.matrix.androidsdk.MXSession.logout(MXSession.java:2133)
08-13 20:09:12.118 26454 26454 E MXSession: 	at im.vector.Matrix.clearSession(Matrix.java:576)
08-13 20:09:12.118 26454 26454 E MXSession: 	at im.vector.Matrix.clearSessions(Matrix.java:617)
08-13 20:09:12.118 26454 26454 E MXSession: 	at im.vector.Matrix.clearSessions(Matrix.java:595)
08-13 20:09:12.118 26454 26454 E MXSession: 	at im.vector.activity.CommonActivityUtils.recoverInvalidatedToken(CommonActivityUtils.java:360)
08-13 20:09:12.118 26454 26454 E MXSession: 	at im.vector.Matrix$5.onConfigurationError(Matrix.java:689)
08-13 20:09:12.118 26454 26454 E MXSession: 	at org.matrix.androidsdk.MXDataHandler.onConfigurationError(MXDataHandler.java:407)
08-13 20:09:12.118 26454 26454 E MXSession: 	at org.matrix.androidsdk.sync.DefaultEventsThreadListener.onConfigurationError(DefaultEventsThreadListener.java:48)
08-13 20:09:12.118 26454 26454 E MXSession: 	at org.matrix.androidsdk.sync.EventsThread$3.onMatrixError(EventsThread.java:661)
08-13 20:09:12.118 26454 26454 E MXSession: 	at org.matrix.androidsdk.rest.callback.RestAdapterCallback.failure(RestAdapterCallback.java:252)
08-13 20:09:12.118 26454 26454 E MXSession: 	at org.matrix.androidsdk.rest.callback.RestAdapterCallback$1.onHttpError(RestAdapterCallback.java:149)
08-13 20:09:12.118 26454 26454 E MXSession: 	at org.matrix.androidsdk.core.rest.DefaultRetrofit2ResponseHandler.handleResponse(DefaultRetrofit2ResponseHandler.java:32)
08-13 20:09:12.118 26454 26454 E MXSession: 	at org.matrix.androidsdk.rest.callback.RestAdapterCallback.handleResponse(RestAdapterCallback.java:139)
08-13 20:09:12.118 26454 26454 E MXSession: 	at org.matrix.androidsdk.rest.callback.RestAdapterCallback.onResponse(RestAdapterCallback.java:132)
08-13 20:09:12.118 26454 26454 E MXSession: 	at retrofit2.ExecutorCallAdapterFactory$ExecutorCallbackCall$1$1.run(ExecutorCallAdapterFactory.java:70)
08-13 20:09:12.118 26454 26454 E MXSession: 	at android.os.Handler.handleCallback(Handler.java:873)
08-13 20:09:12.118 26454 26454 E MXSession: 	at android.os.Handler.dispatchMessage(Handler.java:99)
08-13 20:09:12.118 26454 26454 E MXSession: 	at android.os.Looper.loop(Looper.java:214)
08-13 20:09:12.118 26454 26454 E MXSession: 	at android.app.ActivityThread.main(ActivityThread.java:7037)
08-13 20:09:12.118 26454 26454 E MXSession: 	at java.lang.reflect.Method.invoke(Native Method)
08-13 20:09:12.118 26454 26454 E MXSession: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
08-13 20:09:12.118 26454 26454 E MXSession: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)
08-13 20:09:12.124 26454 26454 E MXSession: Use of a released session
08-13 20:09:12.124 26454 26454 E MXSession: java.lang.Exception: Use of a released session
08-13 20:09:12.124 26454 26454 E MXSession: 	at org.matrix.androidsdk.MXSession.checkIfAlive(MXSession.java:372)
08-13 20:09:12.124 26454 26454 E MXSession: 	at org.matrix.androidsdk.MXSession.getDataHandler(MXSession.java:438)
08-13 20:09:12.124 26454 26454 E MXSession: 	at org.matrix.androidsdk.MXSession.decryptRoomSummaries(MXSession.java:2377)
08-13 20:09:12.124 26454 26454 E MXSession: 	at org.matrix.androidsdk.MXSession.enableCrypto(MXSession.java:2470)
08-13 20:09:12.124 26454 26454 E MXSession: 	at org.matrix.androidsdk.MXSession.logout(MXSession.java:2133)
08-13 20:09:12.124 26454 26454 E MXSession: 	at im.vector.Matrix.clearSession(Matrix.java:576)
08-13 20:09:12.124 26454 26454 E MXSession: 	at im.vector.Matrix.clearSessions(Matrix.java:617)
08-13 20:09:12.124 26454 26454 E MXSession: 	at im.vector.Matrix.clearSessions(Matrix.java:595)
08-13 20:09:12.124 26454 26454 E MXSession: 	at im.vector.activity.CommonActivityUtils.recoverInvalidatedToken(CommonActivityUtils.java:360)
08-13 20:09:12.124 26454 26454 E MXSession: 	at im.vector.Matrix$5.onConfigurationError(Matrix.java:689)
08-13 20:09:12.124 26454 26454 E MXSession: 	at org.matrix.androidsdk.MXDataHandler.onConfigurationError(MXDataHandler.java:407)
08-13 20:09:12.124 26454 26454 E MXSession: 	at org.matrix.androidsdk.sync.DefaultEventsThreadListener.onConfigurationError(DefaultEventsThreadListener.java:48)
08-13 20:09:12.124 26454 26454 E MXSession: 	at org.matrix.androidsdk.sync.EventsThread$3.onMatrixError(EventsThread.java:661)
08-13 20:09:12.124 26454 26454 E MXSession: 	at org.matrix.androidsdk.rest.callback.RestAdapterCallback.failure(RestAdapterCallback.java:252)
08-13 20:09:12.124 26454 26454 E MXSession: 	at org.matrix.androidsdk.rest.callback.RestAdapterCallback$1.onHttpError(RestAdapterCallback.java:149)
08-13 20:09:12.124 26454 26454 E MXSession: 	at org.matrix.androidsdk.core.rest.DefaultRetrofit2ResponseHandler.handleResponse(DefaultRetrofit2ResponseHandler.java:32)
08-13 20:09:12.124 26454 26454 E MXSession: 	at org.matrix.androidsdk.rest.callback.RestAdapterCallback.handleResponse(RestAdapterCallback.java:139)
08-13 20:09:12.124 26454 26454 E MXSession: 	at org.matrix.androidsdk.rest.callback.RestAdapterCallback.onResponse(RestAdapterCallback.java:132)
08-13 20:09:12.124 26454 26454 E MXSession: 	at retrofit2.ExecutorCallAdapterFactory$ExecutorCallbackCall$1$1.run(ExecutorCallAdapterFactory.java:70)
08-13 20:09:12.124 26454 26454 E MXSession: 	at android.os.Handler.handleCallback(Handler.java:873)
08-13 20:09:12.124 26454 26454 E MXSession: 	at android.os.Handler.dispatchMessage(Handler.java:99)
08-13 20:09:12.124 26454 26454 E MXSession: 	at android.os.Looper.loop(Looper.java:214)
08-13 20:09:12.124 26454 26454 E MXSession: 	at android.app.ActivityThread.main(ActivityThread.java:7037)
08-13 20:09:12.124 26454 26454 E MXSession: 	at java.lang.reflect.Method.invoke(Native Method)
08-13 20:09:12.124 26454 26454 E MXSession: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
08-13 20:09:12.124 26454 26454 E MXSession: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)
08-13 20:09:12.124 26454 26454 E MXSession: Use of a released session
08-13 20:09:12.124 26454 26454 E MXSession: java.lang.Exception: Use of a released session
08-13 20:09:12.124 26454 26454 E MXSession: 	at org.matrix.androidsdk.MXSession.checkIfAlive(MXSession.java:372)
08-13 20:09:12.124 26454 26454 E MXSession: 	at org.matrix.androidsdk.MXSession.getDataHandler(MXSession.java:438)
08-13 20:09:12.124 26454 26454 E MXSession: 	at org.matrix.androidsdk.MXSession.decryptRoomSummaries(MXSession.java:2378)
08-13 20:09:12.124 26454 26454 E MXSession: 	at org.matrix.androidsdk.MXSession.enableCrypto(MXSession.java:2470)
08-13 20:09:12.124 26454 26454 E MXSession: 	at org.matrix.androidsdk.MXSession.logout(MXSession.java:2133)
08-13 20:09:12.124 26454 26454 E MXSession: 	at im.vector.Matrix.clearSession(Matrix.java:576)
08-13 20:09:12.124 26454 26454 E MXSession: 	at im.vector.Matrix.clearSessions(Matrix.java:617)
08-13 20:09:12.124 26454 26454 E MXSession: 	at im.vector.Matrix.clearSessions(Matrix.java:595)
08-13 20:09:12.124 26454 26454 E MXSession: 	at im.vector.activity.CommonActivityUtils.recoverInvalidatedToken(CommonActivityUtils.java:360)
08-13 20:09:12.124 26454 26454 E MXSession: 	at im.vector.Matrix$5.onConfigurationError(Matrix.java:689)
08-13 20:09:12.124 26454 26454 E MXSession: 	at org.matrix.androidsdk.MXDataHandler.onConfigurationError(MXDataHandler.java:407)
08-13 20:09:12.124 26454 26454 E MXSession: 	at org.matrix.androidsdk.sync.DefaultEventsThreadListener.onConfigurationError(DefaultEventsThreadListener.java:48)
08-13 20:09:12.124 26454 26454 E MXSession: 	at org.matrix.androidsdk.sync.EventsThread$3.onMatrixError(EventsThread.java:661)
08-13 20:09:12.124 26454 26454 E MXSession: 	at org.matrix.androidsdk.rest.callback.RestAdapterCallback.failure(RestAdapterCallback.java:252)
08-13 20:09:12.124 26454 26454 E MXSession: 	at org.matrix.androidsdk.rest.callback.RestAdapterCallback$1.onHttpError(RestAdapterCallback.java:149)
08-13 20:09:12.124 26454 26454 E MXSession: 	at org.matrix.androidsdk.core.rest.DefaultRetrofit2ResponseHandler.handleResponse(DefaultRetrofit2ResponseHandler.java:32)
08-13 20:09:12.124 26454 26454 E MXSession: 	at org.matrix.androidsdk.rest.callback.RestAdapterCallback.handleResponse(RestAdapterCallback.java:139)
08-13 20:09:12.124 26454 26454 E MXSession: 	at org.matrix.androidsdk.rest.callback.RestAdapterCallback.onResponse(RestAdapterCallback.java:132)
08-13 20:09:12.124 26454 26454 E MXSession: 	at retrofit2.ExecutorCallAdapterFactory$ExecutorCallbackCall$1$1.run(ExecutorCallAdapterFactory.java:70)
08-13 20:09:12.124 26454 26454 E MXSession: 	at android.os.Handler.handleCallback(Handler.java:873)
08-13 20:09:12.124 26454 26454 E MXSession: 	at android.os.Handler.dispatchMessage(Handler.java:99)
08-13 20:09:12.124 26454 26454 E MXSession: 	at android.os.Looper.loop(Looper.java:214)
08-13 20:09:12.124 26454 26454 E MXSession: 	at android.app.ActivityThread.main(ActivityThread.java:7037)
08-13 20:09:12.124 26454 26454 E MXSession: 	at java.lang.reflect.Method.invoke(Native Method)
08-13 20:09:12.124 26454 26454 E MXSession: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
08-13 20:09:12.124 26454 26454 E MXSession: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)
08-13 20:09:12.126 26454 26454 E MXSession: ## clear() was already called
```

### PR DESCRIPTION
**Pull request by BillCarsonFr**
Fixes #3249 
Tested against config with SSO and 3mn expiration.

Riot handles token expiration by 'restarting the app' (exit 0); The issue is that the credentials were cleared from the preferences using apply instead of commit (thus never serialized due to the 'restart')

### CODE REVIEW

File: vector/src/main/java/im/vector/store/LoginStorage.java [hunk 1]
```diff
@@ -199,6 +199,6 @@ public void clear() {
         SharedPreferences prefs = mContext.getSharedPreferences(PREFS_LOGIN, Context.MODE_PRIVATE);
         SharedPreferences.Editor editor = prefs.edit();
         editor.remove(PREFS_KEY_CONNECTION_CONFIGS);
-        editor.apply();
+        editor.commit();
```
Comment (bmarty) [inline vector/src/main/java/im/vector/store/LoginStorage.java]: Add a comment to explain why we do not use `apply{}` as we should always do.
